config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
     resource :favorites, only: [:create, :destroy]
     resources :post_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
      get "search" => "users#search"
  end    
  
  get "/search", to: "searches#search"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @book= Book.find(params[:book_id])
    @comment= current_user.post_comments.new(post_comment_params)
    @comment.book_id= @book.id
    @comment.save
    #redirect_to book_path(book)
  end

  def destroy
    PostComment.find(params[:id]).destroy
    @book=Book.find(params[:book_id])
    #@comment= current_user.post_comments.new(post_comment_params)
    #@comment.book_id= @book.id
    #redirect_to book_path(params[:book_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_counter.html.erb
コメント数： <%= book.post_comments.count %>

app/views/post_comments/_form.html.erb
<%= form_with(model:[book, post_comment], local: false) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder:'コメントをここに', class: "w-100", id: "comment_textarea" %>
  <%= f.submit "送信" %>
<% end %>

app/views/post_comments/_index.html.erb
<table>
  <tbody>
    <% book.post_comments.each do |post_comment| %>
    <tr>
      
      <td>
        <%= link_to user_path(post_comment.user) do %>
          <%= image_tag post_comment.user.get_profile_image, size:"50x50" %><br>
          <%= post_comment.user.name %>
        <% end %>  
      </td>
      <td>
        <%= post_comment.comment %>
      </td>
      <td>
        <% if post_comment.user == current_user %>
          <%= link_to "Destroy",book_post_comment_path(book,post_comment), method: :delete, class: "btn btn-danger pull-right", remote: true %>
        <% end %>  
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/post_comments/create.js.erb
$('#comment_counter').html("<%= j(render 'post_comments/counter', book: @comment.book) %>");
$('#comment_index').html("<%= j(render 'post_comments/index', book: @comment.book) %>");
$('#comment_textarea').val("");

app/views/post_comments/destroy.js.erb
$('#comment_counter').html("<%= j(render 'post_comments/counter', book: @book) %>");
$('#comment_index').html("<%= j(render 'post_comments/index', book: @book) %>");