config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
     resource :favorites, only: [:create, :destroy]
     resources :post_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
      get "search" => "users#search"
  end    
  
  get "/search", to: "searches#search"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower

  has_one_attached :profile_image
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  #フォローしたときの処理
  def follow(user_id)
    followers.create(followed_id: user_id)
  end

  #フォローを外すときの処理
  def unfollow(user_id)
    followers.find_by(followed_id: user_id).destroy
  end

  #フォローしていればtrueを返す
  def following?(user)
    following_users.include?(user)
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name Like ?', content + '%')
    elsif method == 'backward'
      User.where('name Like ?', '%' + content)
    else
      User.where('name Like ?','%' + content + '%')
    end  
  end  
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def create
    @user-User.new(user_params)
    @user.save
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @following_users = @user.following_users
    @follower_users = @user.follower_users
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    @books=Book.all
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def follows
    user = User.find(params[:id])
    @users = user.following_users
  end
  
  def followers
    user = User.find(params[:id])
    @user = user.follower_users
  end
  
  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at Like?', "#{create_at}%"]).count
    end
  end  
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー<%= user.followers.count %></td>
        <td>フォロワー<%= user.followeds.count %></td>
        <td><% unless user == current_user %>
            
             <%= render partial: "relationships/follow_btn", locals: { user: user } %>
             <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
	</tr>
	<tr>
	  <th>Follows</th>
	  <td>
	    <%= link_to follows_user_path(user) do %>
	      <h6><%= user.followers.count %></h6>
	    <% end %>
	  </td>
  </tr>
  <tr>
    <th>Followers</th>
    <td>
      <%= link_to followers_user_path(user) do %>
        <h6><%= user.followeds.count %></h6>
      <% end %>
    </td>
  </tr>
  
</table>

<div class='row'>
  <% unless current_user == user %>
    <td><%= render partial: "relationships/follow_btn", locals: { user: user } %></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/_searcf.html.erb
<h4>検索結果</h4>
<table class="table">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Followers</h2>
<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= image_tag user.get_profile_image, size: '50x50' %>
          <% end %>  
        </td>
        <td><%= user.name %></td>
        <td>
          <%= link_to follows_user_path(user) do %>
            <p>フォロー<%= user.followers.count %></p>
          <% end %>  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/follows.html.erb
<h2>Follows</h2>
  <table class='table'>
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user) do %>
              <%= image_tag user.get_profile_image, size: '50x50' %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td>
            <%= link_to follows_user_path(user) do %>
              <h6>フォロー<%= user.followers.count %></h6>
            <% end %>
          </td>
          <td>
            <%= link_to followers_user_path(user) do %>
              <h6>フォロワー<%= user.followeds.count %></h6>
            <% end %>
          </td>
        </tr>
      <% end %>

    </tbody>
  </table>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'users/index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'search', search_book: @search_book ) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books, book: @book %>

      <h3>投稿数の前日比・前週比</h3>
        <div class="table_width">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>今日の投稿</th>
                <th>昨日の投稿</th>
                <th>前日比</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @today_book.count %></td>
                <td><%= @yesterday_book.count %></td>
              <% if @yesterday_book.count == 0 %>
                <td>前日の投稿は無し</td>
              <% else %>
                <td><% @the_day_before = @today_book.count / @yesterday_book.count %>
                <%= (@the_day_before * 100).round %>%
                </td>
              <% end %>
              </tr>
            </tbody>
          </table>

          <table class="table table-bordered">
            <thead>
              <tr>
                <th>今週の投稿</th>
                <th>先週の投稿</th>
                <th>先週比</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @this_week_book.count %></td>
                <td><%= @last_week_book.count %></td>
              <% if @last_week_book.count == 0 %>
                <td>先週の投稿は無し</td>
              <% else %>
                <td><% @the_week_before = @this_week_book.count.to_f / @last_week_book.count %>
                <%= (@the_week_before * 100).round %>%
                </td>
              <% end %>
              </tr>
            </tbody>
          </table>
          <h2>７日分の投稿数</h2>
          <table class="table table-bordered">
            <tr>
              <th>今日</th>
              <th>１日前</th>
              <th>２日前</th>
              <th>３日前</th>
              <th>４日前</th>
              <th>５日前</th>
              <th>６日前</th>
            </tr>
            <tr>
              <td><%= @books.created_today.count %></td>
              <td><%= @books.created_yesterday.count %></td>
              <td><%= @books.created_2day_ago.count %></td>
              <td><%= @books.created_3day_ago.count %></td>
              <td><%= @books.created_4day_ago.count %></td>
              <td><%= @books.created_5day_ago.count %></td>
              <td><%= @books.created_6day_ago.count %></td>
            </tr>
          </table>
          <canvas id="myLineChart"></canvas>
            <script>
              $(document).on('turbolinks:load',function() {
                var ctx = document.getElementById("myLineChart");
                var myLineChart = new Chart(ctx, {
                  type: 'line',
                  data: {
                    labels: ['６日前', '５日前', '４日前', '３日前', '２日前','1日前', '今日'],
                    datasets: [
                      {
                        label: '投稿した本の数',
                        data: [
                          <%= @books.created_6day_ago.count %>,
                          <%= @books.created_5day_ago.count %>,
                          <%= @books.created_4day_ago.count %>,
                          <%= @books.created_3day_ago.count %>,
                          <%= @books.created_2day_ago.count %>,
                          <%= @books.created_yesterday.count %>,
                          <%= @books.created_today.count %>,
                        ],
                        borderColor: "rgba(0,0,255,1)",
                        backgroundColor: "rgba(0,0,0,0)",
                        tension: 0.4
                      }
                    ],
                  },
                  options: {
                    title: {
                      display: true,
                      text: '７日間の投稿の比較'
                    },
                    responsive: true,
                    scales: {
                      y:{
                        suggestedMin: 0,
                        suggestedMax: 10
                      },
                      x:{
                        stacked: true
                      },
                    },
                  }
                });
              });
            </script>
            
            <%= form_with url:user_search_path(@user), method: :get, local: false do |f| %>
              <%= f.date_field :created_at %>
              <%= f.submit '検索', class: "btn btn-primary" %>
            <% end %>
            
            <div id="search_result">
              <% if @search_book.present? %>
                <%= render 'search', search_book: @search_book %>
              <% end %>  
            </div>
        </div>
    </div>
  </div>
</div>